Spec04 use iotlab-m3 and openmote-b
RIOT-OS/Release-Specs pull request #289
Opened 2023-10-17 12:30 UTC by MrKevinWeiss

The lille site doesn't have any engineers there and all `firefly` boards are have ERROR.

As a result, tests using them are failing.  Since the tests try to use a `cc2538` radio, only `strasbourg` seems to have them, though no samr21-xpros.  So we will have to switch to `iotlab-m3` boards.

2023-10-17 12:30 UTC, MrKevinWeiss commented
Before RC2 we should run this...

2023-10-17 14:09 UTC, miri64 commented
> Before RC2 we should run this...

Have you started a test run?

2023-10-17 14:09 UTC, miri64 commented
Will provide a fix for the failing tests here.

2023-10-17 14:19 UTC, miri64 requested changes
Ah, they are not false negatives! Please run black over `testutils/shell.py`:

```sh
black testutils/shell.py
git commit --fixup 55b4737b7a28cc68a314d2cf24 testutils/shell.py
```

2023-10-17 14:19 UTC, miri64 commented on testutils/shell.py
> +                [addr["addr"] for addr in netif["ipv6_addrs"] if addr["scope"] == scope][0],
```suggestion
                [
                    addr["addr"]
                    for addr in netif["ipv6_addrs"]
                    if addr["scope"] == scope
                ][0],
```

2023-10-17 14:19 UTC, miri64 commented on testutils/shell.py
> +    return first_netif_and_addr_by_scope(ifconfig_out, "link", ignore_chan_0=ignore_chan_0)
```suggestion
    return first_netif_and_addr_by_scope(
        ifconfig_out, "link", ignore_chan_0=ignore_chan_0
    )
```

2023-10-17 17:40 UTC, MrKevinWeiss commented
Yup, ran specific tests and they pass, left work running full `tox`.  I will get to this tomorrow.

2023-10-19 09:38 UTC, MrKevinWeiss commented
We need the openmote pr in the release branch to actually test it... I was getting some flashing errors with the `strasbourg` nodes though...

2023-10-19 11:07 UTC, MrKevinWeiss commented
We need the openmote pr in the release branch to actually test it... I was getting some flashing errors with the `strasbourg` nodes though...

2023-10-19 13:24 UTC, MrKevinWeiss commented
Here is my test result:

```
$ tox -e test -- -k "spec04 and (task05 or task06)"
test: commands[0]> pytest -k 'spec04 and (task05 or task06)'
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.3.2, pluggy-1.3.0 -- /home/weiss/repos/Release-Specs/.tox/test/bin/python
cachedir: .tox/test/.pytest_cache
rootdir: /home/weiss/repos/Release-Specs
configfile: setup.cfg
plugins: rerunfailures-12.0, cov-4.1.0
collected 135 items / 133 deselected / 2 selected                                                                                                                                                                

04-single-hop-6lowpan-icmp/test_spec04.py::test_task05[nodes0-strasbourg] RERUN                                                                                                                            [ 50%]
04-single-hop-6lowpan-icmp/test_spec04.py::test_task05[nodes0-strasbourg] RERUN                                                                                                                            [ 50%]
04-single-hop-6lowpan-icmp/test_spec04.py::test_task05[nodes0-strasbourg] PASSED                                                                                                                           [ 50%]
04-single-hop-6lowpan-icmp/test_spec04.py::test_task06[nodes0-strasbourg] PASSED                                                                                                                           [100%]

---------------------------------------------------------------------- generated xml file: /home/weiss/repos/Release-Specs/test-report.xml -----------------------------------------------------------------------
============================================================================= 2 passed, 133 deselected, 2 rerun in 716.35s (0:11:56) =============================================================================
  test: OK (717.26=setup[0.05]+cmd[717.21] seconds)
  congratulations :) (717.33 seconds)
```
<details>

```
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="0" skipped="0" tests="2" time="716.358" timestamp="2023-10-19T15:02:05.874450" hostname="mobiweiss"><testcase classname="04-single-hop-6lowpan-icmp.test_spec04" name="test_task05[nodes0-strasbourg]" time="482.164"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------
Launching build container using image "docker.io/riot/riotbuild:latest".
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Berlin:/etc/localtime:ro' -v '/home/weiss/repos/RIOT-release-manager/RIOT-release:/data/riotbuild/riotbase:delegated' -v '/home/weiss/.cargo/registry:/data/riotbuild/.cargo/registry:delegated' -v '/home/weiss/.cargo/git:/data/riotbuild/.cargo/git:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e 'BUILD_DIR=/data/riotbuild/riotbase/build' -e 'RIOTPROJECT=/data/riotbuild/riotbase' -e 'RIOTCPU=/data/riotbuild/riotbase/cpu' -e 'RIOTBOARD=/data/riotbuild/riotbase/boards' -e 'RIOTMAKE=/data/riotbuild/riotbase/makefiles'       -e 'USEMODULE=shell_cmd_gnrc_pktbuf' -e 'BOARD=iotlab-m3' -e 'IOTLAB_NODE=m3-10.strasbourg.iot-lab.info' -e 'DISABLE_MODULE=' -e 'DEFAULT_MODULE=' -e 'FEATURES_REQUIRED=' -e 'FEATURES_BLACKLIST=' -e 'FEATURES_OPTIONAL=' -e 'USEMODULE=auto_init_gnrc_netif auto_init_gnrc_rpl gnrc_icmpv6_echo gnrc_icmpv6_error gnrc_ipv6_router_default gnrc_rpl netdev_default netstats_ipv6 netstats_l2 netstats_rpl ps shell shell_cmd_gnrc_pktbuf shell_cmd_gnrc_udp shell_cmds_default' -e 'USEPKG='  -w '/data/riotbuild/riotbase/examples/gnrc_networking/' 'docker.io/riot/riotbuild:latest' make   'EXTERNAL_BOARD_DIRS=/data/riotbuild/riotbase/tests/build_system/external_board_dirs/esp-ci-boards'  
#x1B[1;32mBuilding application "gnrc_networking" for "iotlab-m3" with MCU "stm32".#x1B[0m

"make" -C /data/riotbuild/riotbase/pkg/cmsis/ 
"make" -C /data/riotbuild/riotbase/boards/common/init
"make" -C /data/riotbuild/riotbase/boards/iotlab-m3
"make" -C /data/riotbuild/riotbase/boards/common/iotlab
"make" -C /data/riotbuild/riotbase/core
"make" -C /data/riotbuild/riotbase/core/lib
"make" -C /data/riotbuild/riotbase/cpu/stm32
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common
"make" -C /data/riotbuild/riotbase/cpu/cortexm_common/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/periph
"make" -C /data/riotbuild/riotbase/cpu/stm32/stmclk
"make" -C /data/riotbuild/riotbase/cpu/stm32/vectors
"make" -C /data/riotbuild/riotbase/drivers
"make" -C /data/riotbuild/riotbase/drivers/at86rf2xx
"make" -C /data/riotbuild/riotbase/drivers/netdev
"make" -C /data/riotbuild/riotbase/drivers/periph_common
"make" -C /data/riotbuild/riotbase/sys
"make" -C /data/riotbuild/riotbase/sys/auto_init
"make" -C /data/riotbuild/riotbase/sys/div
"make" -C /data/riotbuild/riotbase/sys/event
"make" -C /data/riotbuild/riotbase/sys/evtimer
"make" -C /data/riotbuild/riotbase/sys/fmt
"make" -C /data/riotbuild/riotbase/sys/frac
"make" -C /data/riotbuild/riotbase/sys/isrpipe
"make" -C /data/riotbuild/riotbase/sys/libc
"make" -C /data/riotbuild/riotbase/sys/luid
"make" -C /data/riotbuild/riotbase/sys/malloc_thread_safe
"make" -C /data/riotbuild/riotbase/sys/net/crosslayer/inet_csum
"make" -C /data/riotbuild/riotbase/sys/net/gnrc
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netapi
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif/hdr
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif/ieee802154
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netif/init_devs
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/netreg
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/icmpv6
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/icmpv6/echo
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/icmpv6/error
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/ipv6
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/ipv6/hdr
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/ipv6/nib
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/ndp
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/ctx
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/frag
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/frag/fb
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/frag/rb
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/iphc
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/network_layer/sixlowpan/nd
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pkt
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pktbuf
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pktbuf_static
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/pktdump
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/routing/rpl
"make" -C /data/riotbuild/riotbase/sys/net/gnrc/transport_layer/udp
"make" -C /data/riotbuild/riotbase/sys/net/link_layer/eui_provider
"make" -C /data/riotbuild/riotbase/sys/net/link_layer/ieee802154
"make" -C /data/riotbuild/riotbase/sys/net/link_layer/l2util
"make" -C /data/riotbuild/riotbase/sys/net/netif
"make" -C /data/riotbuild/riotbase/sys/net/netutils
"make" -C /data/riotbuild/riotbase/sys/net/network_layer/icmpv6
"make" -C /data/riotbuild/riotbase/sys/net/network_layer/ipv6/addr
"make" -C /data/riotbuild/riotbase/sys/net/network_layer/ipv6/hdr
"make" -C /data/riotbuild/riotbase/sys/net/network_layer/sixlowpan
"make" -C /data/riotbuild/riotbase/sys/net/transport_layer/udp
"make" -C /data/riotbuild/riotbase/sys/newlib_syscalls_d [...]

2023-10-19 13:25 UTC, MrKevinWeiss commented
ping @miri64

2023-10-19 15:43 UTC, merged